### ISSUE TITLE
Question about ordering operation 

### ISSUE THREAD

**Issue by iris0329** [Halmstad-University/SalsaNext#18]
Hi, 
Sorry to bother you again!
I find that there is an operation ordering the **points, label and proj_y/proj_x**:

```
indices = np.arange(depth.shape[0])  
order = np.argsort(depth)[::-1]  
depth = depth[order]
indices = indices[order]
points = self.points[order]
remissions = self.remissions[order]

proj_y = self.proj_y[order]
proj_x = self.proj_x[order]
```

I am curisous about the purpose of this operation.
Looking forward to your reply !

Best, 
Iris.

**Comment by TiagoCortinhal** [comment]
Hello @iris0329!

Because we are projecting the PointCloud to a spherical representation we need to ensure that all points rendered in the image are in the current field of view of the LiDAR sensor, for that end the points are ordered in descending order. This is also used when we project each pixel back to the original point cloud.

**Comment by iris0329** [comment]
Thanks
