### ISSUE TITLE
A little mistack

### ISSUE THREAD

**Issue by NariaPetrova** [Halmstad-University/SalsaNext#36]
Hi! According to sentences on top left of Page.2， a mistake may lie in Block Ⅰ of  Fig.2, the kernel size might be 3,5,7 and the  dilation rates of three dilated convolution layers should keep the same.

**Comment by TiagoCortinhal** [comment]
Hello @NariaPetrova!

I am not sure if I understood correctly your question. But the kernel size will be equivalent to 3,5,7 due to the dilatation rate, we will still use actual kernel sizes smaller than the effective size due to the computational cost of operating with higher sizes.

I hope this was your question, if not please correct me where I misunderstood you so we can go to the bottom of your question!
